### PR TITLE
Support local settings

### PR DESCRIPTION
**Pull request by jonallured**
This PR introduces the concept of a local `spellcheck.json` file so that individual repos can whitelist words that make sense for them.

### CODE REVIEW

**Comment by jonallured** [comment]
Also: I've just pushed [a commit](https://github.com/artsy/bearden/commit/3e3ccb6a30845faa919e37b8db9c1f1aea0bdb59) that adds an ignore list for Bearden so that we can test this over there.

**Review by orta — APPROVED** [review]
Looks legit - good cleanup Jon

**Comment by jonallured** [comment]
Thanks for pairing with me on it - I learned a lot!! ❤️

**Comment by orta** [comment]
Shipped in 1.1.0

screen shot 2017-08-31 at 11 32 53

**Comment by orta** [comment]
Will deploy to our peril when https://github.com/danger/peril/pull/141 is green

**Pull request merged**
