### PR TITLE
Function Options Update

### PR DESCRIPTION
**Pull request by GantMan**
As mentioned before these are the fixes for feature mentioned in #13 

I had to moved settings to optional, since I don't care to set it for my needs, but it makes sense to me.

Tested as best as I can using `danger pr` and updated docs.

### CODE REVIEW

**Comment by orta** [comment]
Yep - this is perfect

**Comment by orta** [comment]
As this was my first danger plugin, I hadn't figured out how to make tests for them yet - sorry about that. It's running fine on this PR, so that works for me ;)

**Comment by orta** [comment]
Shipped as ~~1.2.0~~ 1.2.1

**Comment by GantMan** [comment]
giphy 4

**Comment by GantMan** [comment]
@orta - are you sure you did a `tsc` before you published?

I was having issues with 1.2.1 and was like Ummm WHY!  then I openend node_modules, and I'm not seeing the new code in the `dist`.

**Pull request merged**
